### ISSUE TITLE
Add option to commitlint to ignore commit message comments

### ISSUE THREAD

**Issue by Jipi-load** [stasson/standard-commit#21]
When I do commit, git produces a list of changed files that may be longer than 100 caracters. This makes fails the commit.
commitlint tool has the capacity to ignore comments through the parserOpts.commentChar = '#'

I'm not a typescript expert, so ascking here if someone can take it :)

Example of failure
![image](https://github.com/stasson/standard-commit/assets/172837830/8950db9a-788f-4d72-8aaa-e1d1156ba46e)

Using following .standard-commitrc
```
{
  "types": [
    "feat",
    "fix",
    "chore",
    "docs",
    "refactor",
    "test"
  ],
  "enforceIssueRefs": [],
  "issuePrefixes": []
}
```

**Comment by stasson** [comment]
should be fixed with [chore(release): 4.3.0](https://github.com/stasson/standard-commit/commit/161fcac6f625fee323adda2095e1bace9b9d8194)
