### ISSUE TITLE
commit fails when installed locally

### ISSUE THREAD

**Issue by renaud-dc** [stasson/standard-commit#3]
version : 1.0.1

When installed locally, standard-commit CLI doesn't prompt anything and doesn't commit anything as well.

**To reproduce**
_install yorkie (or husky@next)_

npm install --save-dev yorkie standard-commit standard-version

_and setup the scripts and commit-msg hook in your package.json_

{
  "scripts": {
    "commit": "standard-commit",
    "commitlint": "standard-commitlint",
    "release": "standard-version"
  },
  "gitHooks": {
    "commit-msg": "standard-commithook"
  }
}

# use commit script to commit
npm -s run commit

**Comment by stasson** [comment]
fixed with tag 1.1.0
